### ISSUE TITLE
Ideas for reading entity properties from SVGs

### ISSUE THREAD

**Issue by mwcz** [Weasy666/bevy_svg#16]
I'm using Bevy to build a puzzle game whose levels are composed of arbitrary polygons, so an SVG editor is a natural choice for a level editor.  Each `<path>` in the SVG would result in a separate entity, with customized components added to it.  My current idea for how to define which components to add is to put some TOML inside the Description field in Inkscape, which maps to a `<desc>` element inside each `<path>`.

In Inkscape:
![image](https://user-images.githubusercontent.com/364615/193496829-a0e9d8ea-6d8f-4f4f-a63c-7c20df5e4c20.png)

Resulting SVG:
```svg
<path d="m 61.471991,52.652097 37.150462,2.405425 -4.00904,31.003266 -14.699824,-0.801809 z" id="poly2">
  <desc
     id="desc1938"># this is a TOML document

solid = true</desc>
</path>
<path d="M 25.912339,80.186702 39.275815,99.964647 52.639292,78.315814 31.525,57.736062 Z" id="poly1">
  <desc
     id="desc1936"># this is a TOML document

solid = false</desc>
</path>
```

I'm hoping to use bevy_svg's loader, but instead of using `Svg2dBundle` to render the SVG, I'd loop through the `<path>`s and add them each as separate entities with whatever components are defined in the TOML-formatted `<desc>` text.

As I'm writing this I'm starting to think it's too far away from bevy_svg's main use case.  `usvg` for example is exclusively for rendering afaict, certainly not for any kind of "SVG as data structure" usage.  Is there a clever way to use bevy_svg for this purpose, or would a friendly fork be a better option?

Regardless, I'll be using bevy_svg for SVG rendering in other parts of the game.  Thanks for creating it!

**Comment by Weasy666** [comment]
You are welcome! Yeah, the intention is rather for rendering SVGs and not using them as data structure, so i guess a friendly fork would be the initial way to go 🙂. If you come up with a way to integrate it into your fork, without breaking too much or making things too complex, i would be willing to give it a look and maybe integrate into the crate. 🙂

**Comment by mwcz** [comment]
Cool, thanks for the response!  I'll close this for now and perhaps reopen if I get to that point.
