### ISSUE TITLE
README should mention prelude

### ISSUE THREAD

**Issue by hmeine** [Weasy666/bevy_svg#17]
The README is very helpful (more than the docs.rs page – maybe that one should contain the examples from the README as well!), but I had to look into the examples directory to find
```rs
use bevy_svg::prelude::*;
```
so I think that should also be mentioned (below the Cargo.toml instructions).

**Comment by hmeine** [comment]
Oh, and should `SvgBundle` be `Svg2dBundle`?

**Comment by Weasy666** [comment]
Yepp, you are right with the bundle, i have also added the `use bevy_svg::prelude::*;` to the example in the README. Do you think that is enough?
And yeaaaaah...i also really need to give the docs some love 😅
