### ISSUE TITLE
Render incorrectly.

### ISSUE THREAD

**Issue by songww** [Weasy666/bevy_svg#3]
[Twinkle.svg.txt](https://github.com/Weasy666/bevy_svg/files/6670314/Twinkle.svg.txt)

Position wrong .

**Comment by Weasy666** [comment]
Thx for the info. I will take a look at it on the weekend.
But are you sure that your SVG file is correct?

When i open it with Affinity Designer, it looks like this:
![grafik](https://user-images.githubusercontent.com/11967542/122465461-6b88ed80-cfb8-11eb-9831-aba1a3325262.png)

**Comment by songww** [comment]
Thanks.

**Comment by Weasy666** [comment]
Ok, thx for the images. Looks like your file indeed is correct.
I've taken a look at it and know the problem. This plugin currently only draws paths, because that was enough for my use case, so `SVG` and `Group` tags are currently not implemented. I will try and implement them, but it can take a while until i have finished it.

**Comment by songww** [comment]
> Is it ok for you when i add your SVG file to the repository as an example?
It is Ok.

Thank you.

**Comment by Weasy666** [comment]
Hm...i get it to lead everything
![grafik](https://user-images.githubusercontent.com/11967542/127737984-23f58e29-6b25-4f35-aeea-22c6762235cb.png)

but i am somehow hitting a wall with the `defs` and transforming them to their correct positions 😫

**Comment by songww** [comment]
resvg can handle this correctly. maybe it can help us.

**Comment by Weasy666** [comment]
I tried to replicate whot resvg is doing in its [Explorer Thumbnailer](https://github.com/RazrFalcon/resvg/tree/master/tools/explorer-thumbnailer) tool, but i seem to do something wrong regarding the transforms of the linked `defs`.
I am working on the `fix_twinkle` branch

**Comment by Weasy666** [comment]
@mdevlamynck lets actually move the conversation about the fix to the issue.
Great to hear! On which branch is your fix based?

**Comment by mdevlamynck** [comment]
My fix is based on bevy-0.5.

**Comment by Weasy666** [comment]
Ok, then lets use `bevy-0.5` as PR target.

**Comment by Weasy666** [comment]
Fixed in #4 . I will backport font loading and some other refactor changes from `main` branch at the weekend and then release a new patch version. @songww

**Comment by songww** [comment]
Thanks

**Comment by Weasy666** [comment]
Version `0.3.1` is now on crates.io.
`Twinkle.svg` looks now like this:
![grafik](https://user-images.githubusercontent.com/11967542/132939386-136fb9b0-f8f8-4458-a05d-f203df4de194.png)

Thanks again @mdevlamynck!
