### ISSUE TITLE
Support for Bevy main / upcoming 0.11 release

### ISSUE THREAD

**Issue by miketwenty1** [Weasy666/bevy_svg#32]
bevy_svg main branch doesn't currently support bevy's main branch.
```
the trait bound `bevy_svg::SvgPlugin: bevy::prelude::Plugin` is not satisfied
the following other types implement trait `bevy::prelude::Plugin`:
```

Are there plans of supporting main before 0.11 release?

**Comment by Weasy666** [comment]
I haven't tried to keep up with the many changes happening in Bevy, because currently i just don't have the time and energy to chase every change 😅
If the renderer didn't change that much, then you can try and use the `[patch]` section in your `cargo.toml` to point `bevy` to the github repository.
