### ISSUE TITLE
example with shaders

### ISSUE THREAD

**Issue by pyweeker** [Weasy666/bevy_svg#9]
hello, is it possible to get something like this ? if yes, how ?

[https://darkcatgame.tistory.com/83?category=795590](https://darkcatgame.tistory.com/83?category=795590)

**Comment by Weasy666** [comment]
I am not exactly sure how this is related to an SVG, but if you want to use shaders with Bevy, you could take a look at https://github.com/bevyengine/bevy/blob/main/examples/shader/animate_shader.rs

**Comment by pyweeker** [comment]
thanks for the example, sory for the late response
